### ISSUE TITLE
x64应用程序报错

### ISSUE THREAD

**Issue by luy710** [godsharp/opcsample#3]
Hello GodSharpOpcDaSample!
connect to server ...

未经处理的异常:  System.AggregateException: 发生一个或多个错误。 ---> System.Exception: The tag with item name 'Channel1.Device1.Bool' add failed. ---> System.Runtime.InteropServices.COMException: 异常来自 HRESULT:0xC0040007
   在 OPCAutomation.OPCItems.AddItem(String ItemID, Int32 ClientHandle)
   在 GodSharp.Opc.Da.OpcAutomationGroupSubscription.Add(Tag[] tags)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 GodSharp.Opc.Da.OpcAutomationGroupSubscription.Add(Tag[] tags)
   在 GodSharp.Opc.Da.OpcDaClient.Connect()
   在 GodSharpOpcDaSample.Program.Main(String[] args)

**Comment by seayxu** [comment]
opc da 要用 `x86`，要支持 `x64` 使用 `OpcNetApi` 组件。
