### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by avnet78** [godsharp/opcsample#4]
I am following the code provided in the opcsample/Program.cs and I am getting the below exception. Should I register any of the com dll's using regsvr?
Please advise.

System.Runtime.InteropServices.COMException: 'Retrieving the COM class factory for component with CLSID {28E68F9A-8D75-11D1-8DC3-3C302A000000} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).'

These are the dll's inside the bin folder:

![image](https://user-images.githubusercontent.com/63065740/183466635-c986b653-2d54-467a-bc17-41f00a7a176c.png)

**Comment by aevi1103** [comment]
@avnet78  have you fixed this error I have this error too

**Comment by avnet78** [comment]
No, I tried but could not fix it and that’s when I created the issue.

Thanks,
Vishal
________________________________

**Comment by seayxu** [comment]
@aevi1103 @avnet78 If you want to use `OpcAutomation` or `Graybox`, you should register dll, and this is only support `x86`.
If you want to support `x64`, you should use `OpcNetApi` and install `OPC Core Components`.
[Opc Da Introduction](/src/GodSharpOpcDaSample/README.md#introduction)
